import { createLightship } from 'lightship';
import { Command, Option } from "commander";

import { version } from '../package.json';
import { app } from "./app";
// import config from "./config";




/**
 * Sety up CLI options & config
 */
const program = new Command();
program
    .version(version)
    .addOption(
        new Option('-p, --port <port>', 'Port to run the srevice on')
        .default(3000)
        .env('PORT')
        .makeOptionMandatory())
    .addOption(
        new Option('--probes <port>', 'Port to serve /live, /health and /ready probes on.')
        .default(9090)
        .env('PROBES_PORT'))
    .addOption(
        new Option('--cookie-secret <secret>', 'Cookie secret to use in auth. Will be autogenerated if not provided')
        .env('COOKIE_SECRET'))
    .addOption(
        new Option('--callback-path <path>', 'The callback path to receive idp responses on')
        .default('/callback')
        .env('CALLBACK_PATH')
        .makeOptionMandatory())
    .addOption(
        new Option('--oidc-client-id <id>', 'The OIDC client id.')
        .env('OIDC_CLIENT_ID')
        .makeOptionMandatory())
    .addOption(
        new Option('--oidc-client-secret <secret>', 'The OIDC client secret.')
        .env('OIDC_CLIENT_SECRET')
        .makeOptionMandatory())
    .addOption(
        new Option('--oidc-base-url <baseUrl>', 'The base URL for the auth process (eg: https://auth.example.com).')
        .env('OIDC_BASE_URL')
        .makeOptionMandatory())
    .addOption(
        new Option('--oidc-issuer-url <issuerUrl>', 'The OIDC issuer url (eg: https://catalystgamma.eu.auth0.com).')
        .env('OIDC_ISSUER_URL')
        .makeOptionMandatory())
    .showHelpAfterError();

program.parse(process.argv);
const config = program.opts();


// Set up /live, /health and /ready endpoints for kubernetes.
const lightship = createLightship({
    port: config.probes,
    
});

const server = app.listen(config.port, () => {
    const addr = server.address();
    console.log(`Listening on ${addr}`);
    lightship.signalReady();
});


server.on("error", (error: NodeJS.ErrnoException) => {
    lightship.shutdown();

    if (error.syscall !== "listen") {
        throw error;
    }

    // handle specific listen errors with friendly messages
    switch (error.code) {
        case "EACCES":
            console.error(`${config.port} requires elevated privileges`);
            process.exit(1);
            break;
        case "EADDRINUSE":
            console.error(`${config.port} is already in use`);
            process.exit(1);
            break;
        default:
            throw error;
    }
});

// Taken care of by lightship
// process.on('SIGTERM', () => {
//     console.error('SIGTERM signal received: closing HTTP server');
//     server.close(() => {
//         lightship.shutdown();
//         console.error('HTTP server closed');
//     });
// });

// export default server;
